version: '3'

services:
  database:
    image: postgres:9.6
    container_name: python-email-worker.psql
    volumes:
      - storage:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - db

  server:
    image: nginx:1.13
    container_name: python-email-worker.server
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${SERVER_PORT}:80
    networks:
      - web
    depends_on:
      - app

  redis:
    image: redis:3.2
    container_name: python-email-worker.redis
    networks:
      - queue

  worker:
    build: worker
    volumes:
      - ./worker:/worker
    working_dir: /worker
    command: worker.py
    networks:
      - queue
    depends_on:
      - redis

  app:
    image: python:3.6
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    container_name: python-email-worker.app
    networks:
      - db
      - web
      - queue
    depends_on:
      - database
      - redis

volumes:
  storage:

networks:
  db:
  web:
  queue: